"""fix gallery relation and comment link

Revision ID: 5eb73868f984
Revises: f035b9a6b480
Create Date: 2025-10-10 23:32:40.961771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb73868f984'
down_revision = 'f035b9a6b480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_image')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('main_image',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('main_image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    op.create_table('post_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_image_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('post_image_pkey'))
    )
    # ### end Alembic commands ###
