"""fix gallery relation and comment link

Revision ID: 6123b5a2eee0
Revises: 5eb73868f984
Create Date: 2025-10-11 00:01:00.394542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6123b5a2eee0'
down_revision = '5eb73868f984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_main', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.drop_column('is_main')

    # ### end Alembic commands ###
